### ISSUE TITLE
Blackmarket not working

### ISSUE THREAD

**Issue by Kpf1220** [trclassic92/tr-blackmarket#4]
Just installed it and noticed there are two peds on top of each other and I cant third eye to shop or walk up to them and shop.

**Comment by Kpf1220** [comment]
its works on only one guy, its duplicating which is causing this

how do i stop the duplicating?

**Comment by Kpf1220** [comment]
there are two people in blue shirts stacked on top of each other

**Comment by trclassic92** [comment]
It should be fixed now

**Comment by bigdrip187** [comment]
hi everything work till i  third eye the black market seller it  comes up but when i click it no guns comes up
